# Required
version: 2

build:
  os: "ubuntu-20.04"
  tools:
    python: "mambaforge-4.10"

sphinx:
  configuration: doc/conf.py

conda:
    environment: doc/environment.yml

python:
  install:
    - method: pip
      path: .

formats: []
